apiVersion: integration/v1
kind: Step
name: user-get-by-id
version: 1
summary: Get PagerDuty user by ID

description: Gets user details from PagerDuty by their PagerDuty ID.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/pagerduty-step-user-get-by-id

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json

examples:
- summary: Get PagerDuty user by ID
  content:
    apiVersion: v1
    kind: Step
    name: pagerduty-user
    image: relaysh/pagerduty-step-user-get-by-id
    spec:
      connection: !Connection {pagerduty, my-pagerduty-account}
      userID: !Parameter userID
