apiVersion: integration/v1
kind: Step
name: event-send
version: 1
summary: Send PagerDuty event

description: Sends events to PagerDuty.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/pagerduty-step-event-send

schemas:
  spec:
    $schema: 'http://json-schema.org/draft-07/schema#'
    type: object
    properties:
      type:
        type: string
        description: "The kind of event to send; one of 'trigger', 'acknowledge', 'resolve'"
      connection:
        type: object
        x-relay-connectionType: pagerduty
        description: Relay Connection containing PagerDuty credentials
      dedup_key:
        type: string
        description: The deduplication key to group all events relating to an incident
      summary:
        type: string
        description: The summary of the event triggered
      source:
        type: string
        description: The source of the event
      severity:
        type: string
        description: The severity of the event; one of 'info', 'warning', 'error', 'critical'
    required: [connection, type, dedup_key]
  outputs:
    $schema: 'http://json-schema.org/draft-07/schema#'
    type: object
    properties:
      dedup_key:
        type: string
        description: The deduplication key for the referenced event

examples:
- summary: Send new event to PagerDuty
  content:
    apiVersion: v1
    kind: Step
    name: pagerduty-event
    image: relaysh/pagerduty-step-event-send
    spec:
      connection: !Connection { type: pagerduty, name: my-pagerduty-account }
      type: trigger
      summary: !Fn.concat
      - "Host "
      - !Parameter hostname
      - " is down"
      source: !Parameter hostname
      severity: critical
      dedup_key: !Fn.concat ["host-down-", !Parameter hostname]
- summary: Acknowledge an incident in PagerDuty
  content: 
    apiVersion: v1
    kind: Step
    name: acknowledge-event
    image: relaysh/pagerduty-step-event-send
    dependsOn: pagerduty-event
    spec:
      connection: !Connection { type: pagerduty, name: my-pagerduty-account }
      type: acknowledge
      dedup_key: !Fn.concat ["host-down-", !Parameter hostname]
- summary: Resolve an incident in PagerDuty
  content:
    apiVersion: v1
    kind: Step
    name: resolve-event
    image: relaysh/pagerduty-step-event-send
    dependsOn: acknowledge-event
    spec:
      connection: !Connection { type: pagerduty, name: my-pagerduty-account }
      type: resolve
      dedup_key: !Fn.concat ["host-down-", !Parameter hostname]
