apiVersion: integration/v1
kind: Step
name: change-event-send
version: 1
summary: Send PagerDuty change event

description: Sends change events to PagerDuty.

schemas:
  spec:
    source: file
    file: spec.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/pagerduty-step-change-event-send

examples:
- summary: Send change event to PagerDuty
  content:
    apiVersion: v1
    kind: Step
    name: pagerduty-change-event
    image: relaysh/pagerduty-step-change-event-send
    spec:
      connection: !Connection { type: pagerduty, name: my-pagerduty-account }
      summary: !Parameter summary
      source: !Parameter source
